### ISSUE TITLE
Pulling model from cli

### ISSUE THREAD

**Issue by Marcelas751** [CatchTheTornado/pdf-extract-api#12]
root@DESKTOP-5T7CRRP:/mnt/c/Users/user/pdf-extract-api# python3 client/cli.py llm_pull --model llama3.1
Failed to pull the model: Internal Server Error

On "server side":
```
fastapi_app    | INFO:     172.18.0.1:37452 - "POST /llm_pull HTTP/1.1" 500 Internal Server Error
fastapi_app    | ERROR:    Exception in ASGI application
fastapi_app    | Traceback (most recent call last):
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
fastapi_app    |     yield
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
fastapi_app    |     resp = self._pool.handle_request(req)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
fastapi_app    |     raise exc from None
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
fastapi_app    |     response = connection.handle_request(
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
fastapi_app    |     raise exc
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
fastapi_app    |     stream = self._connect(request)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
fastapi_app    |     stream = self._network_backend.connect_tcp(**kwargs)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
fastapi_app    |     with map_exceptions(exc_map):
fastapi_app    |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
fastapi_app    |     self.gen.throw(typ, value, traceback)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
fastapi_app    |     raise to_exc(exc) from exc
fastapi_app    | httpcore.ConnectError: [Errno 111] Connection refused
fastapi_app    |
fastapi_app    | The above exception was the direct cause of the following exception:
fastapi_app    |
fastapi_app    | Traceback (most recent call last):
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
fastapi_app    |     result = await app(  # type: ignore[func-returns-value]
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
fastapi_app    |     return await self.app(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
fastapi_app    |     await super().__call__(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
fastapi_app    |     await self.middleware_stack(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
fastapi_app    |     raise exc
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
fastapi_app    |     await self.app(scope, receive, _send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
fastapi_app    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi_app    |     raise exc
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi_app    |     await app(scope, receive, sender)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
fastapi_app    |     await self.middleware_stack(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
fastapi_app    |     await route.handle(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
fastapi_app    |     await self.app(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
fastapi_app    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
fastapi_app    |     raise exc
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
fastapi_app    |     await app(scope, receive, sender)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
fastapi_app    |     response = await f(request)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
fastapi_app    |     raw_response = await run_endpoint_function(
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
fastapi_app    |     return await dependant.call(**values)
fastapi_app    |   File "/app/main.py", line 91, in pull_llama
fastapi_app    |     response = ollama.pull(request.model)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 319, in pull
fastapi_app    |     return self._request_stream(
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 99, in _request_stream
fastapi_app    |     return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/ollama/_client.py", line 70, in _request
fastapi_app    |     response = self._client.request(method, url, **kwargs)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 837, in request
fastapi_app    |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
fastapi_app    |     response = self._send_handling_auth(
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
fastapi_app    |     response = self._send_handling_redirects(
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
fastapi_app    |     response = self._send_single_request(request)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
fastapi_app    |     response = transport.handle_request(request)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 235, in handle_request
fastapi_app    |     with map_httpcore_exceptions():
fastapi_app    |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
fastapi_app    |     self.gen.throw(typ, value, traceback)
fastapi_app    |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
fastapi_app    |     raise mapped_exc(message) from exc
fastapi_app    | httpx.ConnectError: [Errno 111] Connection refused
```

**Comment by bitdeep** [comment]
Any solution for this? It keep shitting itself all time.

**Comment by pkarw** [comment]
@Marcelas751 @bitdeep I think this is something with env variables, checking out ...

**Comment by pkarw** [comment]
There was a typo in the `docker-compose.yml` :/ Guys please check https://github.com/CatchTheTornado/pdf-extract-api/pull/17
